### ISSUE TITLE
Error in BST.c in Programs of DSA folder

### ISSUE THREAD

**Issue by Saad2714** [Saad2714/My_College_Studies#1]
bst.c: In function ‘insert’:
bst.c:40:3: error: ‘left_level’ undeclared (first use in this function)
   left_level+=1;
   ^~~~~~~~~~
bst.c:40:3: note: each undeclared identifier is reported only once for each function it appears in
bst.c:44:2: error: ‘right_level’ undeclared (first use in this function); did you mean ‘left_level’?
  right_level+=1;
  ^~~~~~~~~~~
  left_level

**Comment by Saad2714** [comment]
@sal2701 please solve this issue

**Comment by Saad2714** [comment]
@sal2701 @AnishRaj2000 please solve this issue

**Comment by anish-rajan** [comment]
I want to take up this issue
